export const Config = {
  EMOJI_LIST: [
    '😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂',
    '🙂', '🙃', '😉', '😊', '😇', '🥰', '😍', '🤩',
    '😘', '😗', '😚', '😙', '😋', '😛', '😜', '🤪',
    '😝', '🤑', '🤗', '🤭', '🤫', '🤔', '🤐', '🤨',
    '😐', '😑', '😶', '😏', '😒', '🙄', '😬', '🤥',
    '😌', '😔', '😪', '🤤', '😴', '😷', '🤒', '🤕',
    '🤢', '🤮', '🤧', '🥵', '🥶', '😶‍🌫️', '🥴', '😵',
    '🤯', '🤠', '🥳', '😎', '🤓', '🧐', '😕', '😟',
    '🙁', '😮', '😯', '😲', '😳', '🥺', '😦', '😧',
    '😨', '😰', '😥', '😢', '😭', '😱', '😖', '😣',
    '😞', '😓', '😩', '😫', '🥱', '😤', '😡', '😠',
    '🤬', '😈', '👿', '💀', '☠️', '💩', '🤡', '👹',
    '👺', '👻', '👽', '👾', '🤖', '😺', '😸', '😹',
    '😻', '😼', '😽', '🙀', '😿', '😾',
    '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍',
    '🤎', '💔', '❣️', '💕', '💞', '💓', '💗', '💖',
    '💘', '💝', '💟', '☮️', '✝️', '☪️', '🕉️', '☸️',
    '✡️', '🔯', '🕎', '☯️', '☦️', '🛐', '⛎', '♈',
    '👍', '👎', '👌', '✌️', '🤞', '🤟', '🤘', '🤙',
    '👈', '👉', '👆', '👇', '☝️', '✋', '🤚', '🖐️',
    '🖖', '👋', '🤙', '💪', '🦾', '🖕', '✍️', '🙏',
    '🔥', '💯', '✨', '🎉', '🎊', '🎈', '🎁', '🏆',
  ],
  PREFETCH_NEIGHBORS: true,
  PREFETCH_MARGIN: "150%",
  UNLOAD_FAR_SLIDES: true,
  FAR_DISTANCE: 2,
  LOW_DATA_MODE: false,
  METRICS_ENDPOINT: "/api/tt-metrics",
  DEBUG_PANEL: true,
  GESTURE_GRACE_PERIOD_MS: 2000,
  TRANSLATIONS: {
    pl: {
      loggedOutText: "Nie masz psychy się zalogować",
      loggedInText: "Ting Tong",
      loginSuccess: "Zalogowano pomyślnie!",
      loginFailed: "Logowanie nie powiodło się. Spróbuj ponownie.",
      accountHeaderText: "Konto",
      menuAriaLabel: "Menu",
      subscribeAriaLabel: "subskrajbować",
      shareTitle: "Udostępnij",
      shareAriaLabel: "Udostępnij",
      shareText: "Szeruj",
      tipTitle: "Napiwek",
      tipAriaLabel: "Napiwek",
      tipText: "Napiwek",
      languageAriaLabel: "Zmień język",
      languageText: "PL",
      subscribeAlert: "Zaloguj się, aby subskrajbować.",
      profileViewAlert: "Zaloguj sie aby zajrzec",
      likeAlert: "Zaloguj się, aby lajkować.",
      notificationAlert: "Zaloguj się i bądź na bieżąco.",
      menuAccessAlert: "Zaloguj się, aby uzyskać dostęp do menu.",
      logoutSuccess: "Zostałeś wylogowany.",
      likeError: "Błąd komunikacji z serwerem.",
      secretTitle: "Ściśle Tajne",
      secretSubtitleAction: "Zaloguj się,",
      secretSubtitleRest: " aby odblokować",
      pwaTitle: "Ściśle Tajne",
      pwaSubtitleAction: "Pobierz aplikację,",
      pwaSubtitleRest: " aby zobaczyć",
      pwaSecretSubtitleAction: "Ściągnij apkę",
      pwaSecretSubtitleRest: ", aby obczaić.",
      closeAccountAriaLabel: "Zamknij panel konta",
      accountMenuButton: "Konto",
      logoutLink: "Wyloguj",
      profileTab: "Profil",
      passwordTab: "Hasło",
      deleteTab: "Usuń konto",
      loggedInState: "Zalogowany",
      loggedOutState: "Gość",
      linkCopied: "Link skopiowany do schowka!",
      likeAriaLabel: "Polub",
      notificationAriaLabel: "Powiadomienia",
      commentsAriaLabel: "Komentarze",
      commentsModalTitle: "Komentarze",
      closeCommentsAriaLabel: "Zamknij komentarze",
      likeAriaLabelWithCount: "Polub. Aktualna liczba polubień: {count}",
      unlikeAriaLabelWithCount:
        "Cofnij polubienie. Aktualna liczba polubień: {count}",
      notificationsTitle: "Powiadomienia",
      closeNotificationsAriaLabel: "Zamknij powiadomienia",
      notificationsEmpty: "Wszystko na bieżąco!",
      notif1Preview: "Nowa wiadomość od Admina",
      notif1Time: "2 min temu",
      notif1Full:
        "Cześć! Chcieliśmy tylko dać znać, że nowa wersja aplikacji jest już dostępna. Sprawdź nowe funkcje w panelu konta!",
      notif2Preview: "Twój profil został zaktualizowany",
      notif2Time: "10 min temu",
      notif2Full:
        "Twoje zmiany w profilu zostały pomyślnie zapisane. Możesz je przejrzeć w dowolnym momencie, klikając w swój awatar.",
      notif3Preview: "Specjalna oferta czeka na Ciebie!",
      notif3Time: "1 godz. temu",
      notif3Full:
        "Nie przegap! Przygotowaliśmy dla Ciebie specjalną letnią promocję. Zgarnij dodatkowe bonusy już teraz. Oferta ograniczona czasowo.",
      pwaModalTitle: "Pełne doświadczenie Ting Tong na Twoim telefonie!",
      pwaModalBody:
        "Zeskanuj kod QR lub odwiedź nas na telefonie, aby pobrać aplikację i odblokować pełne możliwości.",
      installPwaHeading: "Pobierz apkę!",
      installPwaFullDescription: "Zainstaluj Ting Tonga na swoim telefonie.",
      installPwaAction: "Zainstaluj",
      openPwaAction: "Otwórz",
      videoErrorTitle: "Błąd Wideo",
      videoErrorSubtitle: "Nie można załadować materiału.",
      videoErrorRetry: "Spróbuj ponownie",
      alreadyInstalledToast: "Aplikacja jest już zainstalowana.",
      pwaAlreadyInstalled: "Przecież już ściągnąłeś.",
      pwaNotSupported: "Instalacja nie jest wspierana na tej przeglądarce.",
      installNotReadyText: "Instalacja nie jest obecnie możliwa na tej przeglądarce lub urządzeniu.",
      appInstalledSuccessText: "Aplikacja została pomyślnie zainstalowana!",
      tippingTitle: {
        pl: "Bramka Napiwkowa",
        en: "Tipping Gateway",
      },
      tippingStep1Desc: {
          pl: "Założyć konto Patrona? 🏆",
          en: "Become a Love Patron and support the project's development. 🏆"
      },
      tippingCreateAccountLabel: {
          pl: "No raczej!",
          en: "Create a patron account?"
      },
      emailPlaceholder: {
        pl: "(podaj mail na ktory otrzymasz klucze logowania)",
        en: "(enter the email where you will receive your login credentials)"
      },
      tippingEmailHint: {
          pl: "Na podany e-mail otrzymasz dane dostępu do logowania do sekcji dla patronów.",
          en: "You will receive login details for the patron section to the provided email."
      },
      tippingStep2Desc: {
          pl: "Wybierz kwotę, którą chcesz wesprzeć projekt.",
          en: "Choose the amount you want to support the project with."
      },
      tippingAmountPlaceholder: {
          pl: "Wpisz kwotę",
          en: "Enter amount"
      },
      tippingAmountHint: {
          pl: "Minimalna kwota to 1 EUR. Dziękujemy za każde wsparcie!",
          en: "The minimum amount is 1 EUR. Thank you for all your support!"
      },
      tippingStep3Desc: {
          pl: "Przekierowanie do płatności...",
          en: "Redirecting to payment..."
      },
      tippingRedirectHint: {
          pl: "Za chwilę zostaniesz przekierowany do bezpiecznej bramki płatności Stripe.",
          en: "You will be redirected to the secure Stripe payment gateway shortly."
      },
    profileAccessAlert: {
      pl: "Zaloguj się, aby zobaczyć profil.",
      en: "Log in to view the profile.",
    },
      tippingPrev: {
          pl: "Wstecz",
          en: "Back"
      },
      tippingNext: {
          pl: "ENTER",
          en: "ENTER"
      },
      tippingSubmit: {
          pl: "Przejdź do płatności",
          en: "Proceed to Payment"
      },
      tippingSuccessMessage: {
        pl: "Dziękujemy za napiwek w wysokości {amount} EUR!",
        en: "Thank you for your {amount} EUR tip!",
      },
      errorInvalidEmail: {
        pl: "Proszę podać poprawny adres email.",
        en: "Please provide a valid email address.",
      },
      errorMinTipAmount: {
        pl: "Minimalna kwota napiwku to 1 EUR.",
        en: "The minimum tip amount is 1 EUR.",
      },
      noComments: "Brak komentarzy. Bądź pierwszy!",
      commentSortTriggerText: "Sortuj według: ",
      commentSortNewest: "Fresz",
      commentSortBest: "Best",
      toggleRepliesShow: "Rozwiń odpowiedzi ({count})",
      toggleRepliesHide: "Ukryj odpowiedzi",
      loginToCommentAction: "Zaloguj się",
      loginToCommentRest: ", aby dodać komentarz.",
      addCommentPlaceholder: "Dodaj komentarz...",
      sendCommentAriaLabel: "Wyślij komentarz",
      commentReplyAction: "Reply",
      replyingTo: "Odpowiadasz @{user}",
      cancelReplyAriaLabel: "Anuluj odpowiedź",
      failedToUpdateLike: "Nie udało się zaktualizować polubienia.",
      accountModalTitleProfile: "Profil",
      accountModalTitlePassword: "Hasło",
      accountModalTitleDelete: "Usuń konto",
      avatarEditBtnTitle: "Zmień avatar",
      patronBadgeText: "Patron Miłości",
      personalDataHeader: "Dane osobowe",
      firstNameLabel: "Imię",
      firstNamePlaceholder: "Twoje imię",
      lastNameLabel: "Nazwisko",
      lastNamePlaceholder: "Twoje nazwisko",
      emailLabel: "Email",
      emailPlaceholder: "email@domena.pl",
      saveProfileBtn: "Zapisz zmiany",
      settingsHeader: "Ustawienia",
      emailConsentLabel: "Zgoda na maile",
      emailLanguageLabel: "Język maili",
      emailLangPolish: "Polski",
      emailLangEnglish: "English",
      saveSettingsBtn: "Zapisz ustawienia",
      changePasswordHeader: "Zmiana hasła",
      currentPasswordLabel: "Obecne hasło",
      currentPasswordPlaceholder: "Wprowadź obecne hasło",
      newPasswordLabel: "Nowe hasło",
      newPasswordPlaceholder: "Minimum 8 znaków",
      confirmPasswordLabel: "Powtórz nowe hasło",
      confirmPasswordPlaceholder: "Powtórz nowe hasło",
      passwordHelperText:
        "Hasło musi zawierać minimum 8 znaków. Zalecamy użycie liter, cyfr i znaków specjalnych.",
      changePasswordBtn: "Zmień hasło",
      deleteAccountHeader: "Usuń konto",
      deleteWarningHeader: "⚠️ Uwaga!",
      deleteWarningBody:
        "Ta operacja jest nieodwracalna. Wszystkie Twoje dane, filmy i ustawienia zostaną trwale usunięte.",
      deleteConfirmationLabel:
        "Aby potwierdzić, wpisz: <strong>USUWAM KONTO</strong>",
      deleteConfirmationPlaceholder: "USUWAM KONTO",
      deleteHelperText:
        "Po usunięciu konta zostaniesz automatycznie wylogowany.",
      deleteAccountBtn: "Trwale usuń konto",
      profileFollowingLabel: "Obserwuje",
      profileFollowersLabel: "Obserwujący",
      profileLikesLabel: "Polubienia",
      profileFollowBtn: "Obserwuj",
      savingButtonText: "Zapisywanie...",
      changingButtonText: "Zmienianie...",
      deletingButtonText: "Usuwanie...",
      settingsUpdateSuccess: "Ustawienia zostały zapisane! (DEMO)",
      settingsUpdateError: "Wystąpił błąd podczas zapisywania ustawień.",
      fileSelectImageError: "Proszę wybrać plik obrazu.",
      fileTooLargeError: "Plik jest za duży. Maksymalny rozmiar to 5MB.",
      avatarUpdateSuccess: "Avatar został zaktualizowany!",
      avatarUpdateError: "Nie otrzymano URL avatara",
      imageProcessingError: "Błąd podczas przetwarzania obrazu.",
      allFieldsRequiredError: "Wszystkie pola są wymagane.",
      invalidEmailError: "Podaj prawidłowy adres email.",
      profileUpdateSuccess: "Profil został zaktualizowany!",
      profileUpdateError: "Wystąpił błąd podczas aktualizacji profilu.",
      profileUpdateFailedError: "Błąd aktualizacji profilu.",
      passwordUpdateSuccess: "Hasło zostało zmienione!",
      passwordUpdateError: "Błąd zmiany hasła.",
      passwordLengthError: "Nowe hasło musi mieć minimum 8 znaków.",
      passwordsMismatchError: "Nowe hasła muszą być identyczne.",
      passwordChangeFailedError: "Błąd zmiany hasła.",
      deleteAccountSuccess: "Konto zostało usunięte. Trwa wylogowywanie...",
      deleteAccountError: "Błąd usuwania konta.",
      deleteAccountFailedError: "Błąd usuwania konta.",
      deleteConfirmationError: "Wpisz dokładnie: {confirmationText}",
      deleteConfirmationString: "USUWAM KONTO",
      postCommentError: "Nie udało się opublikować komentarza.",
      commentEditAction: "Edytuj",
      commentDeleteAction: "Usuń",
      deleteCommentConfirm: "Czy na pewno chcesz usunąć ten komentarz?",
      editCommentPrompt: "Edytuj swój komentarz:",
      commentUpdateSuccess: "Komentarz zaktualizowany.",
      commentUpdateError: "Nie udało się zaktualizować komentarza.",
      commentDeleteSuccess: "Komentarz usunięty.",
      commentDeleteError: "Nie udało się usunąć komentarza.",
      postCommentSuccess: "Komentarz został opublikowany!",
      passwordStrengthWeak: "Słabe hasło",
      passwordStrengthMedium: "Średnie hasło",
      passwordStrengthStrong: "Silne hasło",
      uploadingAvatar: "Przesyłanie avatara...",
      avatarUploadError: "Nie udało się przesłać avatara",
      commentLoadError: "Nie udało się załadować komentarzy",
      retry: "Spróbuj ponownie",
      imageInputError: "Nie można załączyć obrazu",
      fileReadError: "Nie można odczytać pliku",
      immersiveModePwaOnly: "Działa w apce",

      // --- KLUCZE DLA MODALA PIERWSZEGO LOGOWANIA ---
      firstLoginTitle: "Uzupełnij Profil 🚀", // FIX: Optymistyczny akcent
      firstLoginPrev: "Wstecz",
      firstLoginNext: "Dalej",
      firstLoginSubmit: "Zakończ 🎯",
      firstLoginStep1Desc: "Cieszymy się, że dołączyłeś! 😊<br>Na start możesz zdecydować, czy chcesz otrzymywać od nas maile z nowościami i poradami.",
      firstLoginConsentLabel: "Chcę otrzymywać maile",
      emailLangPolish: "Polski",
      emailLangEnglish: "English",
      firstLoginStep2Desc: "Powiedz nam, jak się nazywasz (lub wymyśl coś kreatywnego 😉).",
      firstLoginNameHint: "Nie musisz podawać prawdziwego imienia i nazwiska.",
      firstLoginStep3Desc: "Świetnie! 🎉<br>Do logowania będziesz używać swojego adresu e-mail:",
      firstLoginPasswordDesc: "Twoje konto zostało utworzone z hasłem tymczasowym. Ustaw teraz nowe, bezpieczne hasło.",
      errorMinPasswordLength: 'Hasło musi mieć co najmniej 8 znaków.',
      errorPasswordsMismatch: 'Wprowadzone hasła nie są identyczne.',
      errorMissingNames: 'Imię i nazwisko są polami wymaganymi.',
      errorPasswordRequired: 'Musisz ustawić nowe hasło.',
      firstNamePlaceholder: "Imię",
      lastNamePlaceholder: "Nazwisko",
      newPasswordPlaceholder: "Nowe hasło",
      confirmPasswordPlaceholder: "Powtórz hasło",
      genericError: "Wystąpił nieoczekiwany błąd. Spróbuj ponownie.",
      timeJustNow: 'teraz',
      timeMinute: 'm',
      timeHour: 'h',
      timeDay: 'd',
    }, // KONIEC 'pl'
    en: {
      loggedOutText: "You don't have the guts to log in",
      loggedInText: "You are logged in",
      loginSuccess: "Logged in successfully!",
      loginFailed: "Login failed. Please try again.",
      accountHeaderText: "Account",
      menuAriaLabel: "Menu",
      subscribeAriaLabel: "Subscribe",
      shareTitle: "Share",
      shareAriaLabel: "Share",
      shareText: "Share",
      tipTitle: "Tip",
      tipAriaLabel: "Tip",
      tipText: "Tip",
      languageAriaLabel: "Change language",
      languageText: "EN",
      subscribeAlert: "Log in to subscribe.",
      profileViewAlert: "Log in to see the profile.",
      likeAlert: "Log in to like.",
      notificationAlert: "Log in to stay up to date.",
      menuAccessAlert: "Log in to access the menu.",
      logoutSuccess: "You have been logged out.",
      likeError: "Server communication error.",
      secretTitle: "Top Secret",
      secretSubtitleAction: "Log in",
      secretSubtitleRest: " to unlock",
      pwaTitle: "Top Secret",
      pwaSubtitleAction: "Download the app",
      pwaSubtitleRest: " to view",
      pwaSecretSubtitleAction: "Download the app",
      pwaSecretSubtitleRest: " to check it out.",
      closeAccountAriaLabel: "Close account panel",
      accountMenuButton: "Account",
      logoutLink: "Logout",
      profileTab: "Profile",
      passwordTab: "Password",
      deleteTab: "Delete account",
      loggedInState: "Logged In",
      loggedOutState: "Guest",
      linkCopied: "Link copied to clipboard!",
      likeAriaLabel: "Like",
      notificationAriaLabel: "Notifications",
      commentsAriaLabel: "Comments",
      commentsModalTitle: "Comments",
      closeCommentsAriaLabel: "Close comments",
      likeAriaLabelWithCount: "Like. Current likes: {count}",
      unlikeAriaLabelWithCount: "Unlike. Current likes: {count}",
      notificationsTitle: "Notifications",
      closeNotificationsAriaLabel: "Close notifications",
      notificationsEmpty: "You are all caught up!",
      notif1Preview: "New message from Admin",
      notif1Time: "2 mins ago",
      notif1Full:
        "Hi there! Just wanted to let you know that a new version of the app is available. Check out the new features in your account panel!",
      notif2Preview: "Your profile has been updated",
      notif2Time: "10 mins ago",
      notif2Full:
        "Your profile changes have been saved successfully. You can review them anytime by clicking on your avatar.",
      notif3Preview: "A special offer is waiting for you!",
      notif3Time: "1 hour ago",
      notif3Full:
        "Don't miss out! We have prepared a special summer promotion just for you. Grab your extra bonuses now. Limited time offer.",
      pwaModalTitle: "The full Ting Tong experience is on your phone!",
      pwaModalBody:
        "Scan the QR code below or visit us on your phone to download the app and unlock the full experience.",
      installPwaHeading: "See more!",
      installPwaFullDescription: "Install Ting Tong on your phone.",
      installPwaAction: "Install",
      openPwaAction: "Open",
      videoErrorTitle: "Video Error",
      videoErrorSubtitle: "Could not load the content.",
      videoErrorRetry: "Try Again",
      alreadyInstalledToast: "The application is already installed.",
      installNotReadyText: "Installation is not currently possible on this browser or device.",
      appInstalledSuccessText: "Application has been installed successfully!",
      noComments: "No comments yet. Be the first!",
      commentSortTriggerText: "Sort by: ",
      commentSortNewest: "Newest",
      commentSortBest: "Best",
      toggleRepliesShow: "Show replies ({count})",
      toggleRepliesHide: "Hide replies",
      loginToCommentAction: "Log in",
      loginToCommentRest: " to add a comment.",
      addCommentPlaceholder: "Add a comment...",
      sendCommentAriaLabel: "Send comment",
      commentReplyAction: "Reply",
      replyingTo: "Replying to @{user}",
      cancelReplyAriaLabel: "Cancel reply",
      failedToUpdateLike: "Failed to update like.",
      accountModalTitleProfile: "Profile",
      accountModalTitlePassword: "Password",
      accountModalTitleDelete: "Delete Account",
      avatarEditBtnTitle: "Change avatar",
      patronBadgeText: "Patron of Love",
      personalDataHeader: "Personal Data",
      firstNameLabel: "First Name",
      firstNamePlaceholder: "Your first name",
      lastNameLabel: "Last Name",
      lastNamePlaceholder: "Your last name",
      emailLabel: "Email",
      emailPlaceholder: "email@domain.com",
      saveProfileBtn: "Save changes",
      settingsHeader: "Settings",
      emailConsentLabel: "Email Consent",
      emailLanguageLabel: "Email Language",
      emailLangPolish: "Polish",
      emailLangEnglish: "English",
      saveSettingsBtn: "Save settings",
      changePasswordHeader: "Change Password",
      currentPasswordLabel: "Current Password",
      currentPasswordPlaceholder: "Enter current password",
      newPasswordLabel: "New Password",
      newPasswordPlaceholder: "Minimum 8 characters",
      confirmPasswordLabel: "Repeat new password",
      confirmPasswordPlaceholder: "Repeat new password",
      passwordHelperText:
        "Password must be at least 8 characters long. We recommend using letters, numbers, and special characters.",
      changePasswordBtn: "Change password",
      deleteAccountHeader: "Delete Account",
      deleteWarningHeader: "⚠️ Warning!",
      deleteWarningBody:
        "This operation is irreversible. All your data, videos, and settings will be permanently deleted.",
      deleteConfirmationLabel:
        "To confirm, type: <strong>DELETE ACCOUNT</strong>",
      deleteConfirmationPlaceholder: "DELETE ACCOUNT",
      deleteHelperText:
        "After deleting your account, you will be automatically logged out.",
      deleteAccountBtn: "Permanently delete account",
      profileFollowingLabel: "Following",
      profileFollowersLabel: "Followers",
      profileLikesLabel: "Likes",
      profileFollowBtn: "Follow",
      savingButtonText: "Saving...",
      changingButtonText: "Changing...",
      deletingButtonText: "Deleting...",
      settingsUpdateSuccess: "Settings have been saved! (DEMO)",
      settingsUpdateError: "An error occurred while saving settings.",
      fileSelectImageError: "Please select an image file.",
      fileTooLargeError: "File is too large. Maximum size is 5MB.",
      avatarUpdateSuccess: "Avatar has been updated!",
      avatarUpdateError: "Avatar URL not received",
      imageProcessingError: "Error processing image.",
      allFieldsRequiredError: "All fields are required.",
      invalidEmailError: "Please provide a valid email address.",
      profileUpdateSuccess: "Profile has been updated!",
      profileUpdateError: "An error occurred while updating the profile.",
      profileUpdateFailedError: "Profile update failed.",
      passwordUpdateSuccess: "Password has been changed!",
      passwordUpdateError: "Error changing password.",
      passwordLengthError: "New password must be at least 8 characters long.",
      passwordsMismatchError: "New passwords must be identical.",
      passwordChangeFailedError: "Password change failed.",
      deleteAccountSuccess: "Account has been deleted. Logging you out...",
      deleteAccountError: "Error deleting account.",
      deleteAccountFailedError: "Account deletion failed.",
      deleteConfirmationError: "Please type exactly: {confirmationText}",
      deleteConfirmationString: "DELETE ACCOUNT",
      postCommentSuccess: "Comment published successfully!",
      passwordStrengthWeak: "Weak password",
      passwordStrengthMedium: "Medium password",
      passwordStrengthStrong: "Strong password",
      uploadingAvatar: "Uploading avatar...",
      avatarUploadError: "Failed to upload avatar",
      commentLoadError: "Failed to load comments",
      retry: "Try again",
      imageInputError: "Cannot attach image",
      fileReadError: "Cannot read file",
      immersiveModePwaOnly: "Works in app",

      // --- KEYS FOR FIRST LOGIN MODAL ---
      firstLoginTitle: "Complete Profile 🚀", // FIX: Optymistyczny akcent
      firstLoginPrev: "Back",
      firstLoginNext: "Next",
      firstLoginSubmit: "Finish 🎯",
      firstLoginStep1Desc: "We're glad you joined! 😊<br>To start, you can decide if you want to receive emails from us with news and tips.",
      firstLoginConsentLabel: "I want to receive emails",
      emailLangPolish: "Polish",
      emailLangEnglish: "English",
      firstLoginStep2Desc: "Tell us your name (or come up with something creative 😉).",
      firstLoginNameHint: "You don't have to use your real name.",
      firstLoginStep3Desc: "Great! 🎉<br>You'll use your email address to log in:",
      firstLoginPasswordDesc: "Your account was created with a temporary password. Please set a new, secure password now.",
      errorMinPasswordLength: 'Password must be at least 8 characters long.',
      errorPasswordsMismatch: 'The entered passwords do not match.',
      errorMissingNames: 'First and last name are required fields.',
      errorPasswordRequired: 'You must set a new password.',
      firstNamePlaceholder: "First Name",
      lastNamePlaceholder: "Last Name",
      newPasswordPlaceholder: "New Password",
      confirmPasswordPlaceholder: "Confirm Password",
      genericError: "An unexpected error occurred. Please try again.",
      timeJustNow: 'now',
      timeMinute: 'm',
      timeHour: 'h',
      timeDay: 'd',
    }, // KONIEC 'en'
  },
};