name: Auto Merge
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
